spring:
    config:
        activate:
            on-profile: dev
    devtools:
        add-properties: true
    data:
        mongodb:
            # uri: mongodb+srv://doankhoe0809_db_user:Tdk08092004@cluster0.t4usdr8.mongodb.net/?appName=Cluster0
            uri: mongodb+srv://meimeidev04_db_user:123456Xyz@cluster0.oyeqeds.mongodb.net/?appName=Cluster0
            database: OTT_Education
    jackson:
        time-zone: Asia/Ho_Chi_Minh
    mail:
        host: smtp.gmail.com
        port: 587
        username: doankhoe0809@gmail.com
        password: qshwxmslwmslscmb
        reset-code-expiry-minutes: 10
        properties:
            mail:
                smtp:
                    auth: true
                    starttls:
                        enable: true
    servlet:
        multipart:
            max-file-size: 10MB
            max-request-size: 10MB
            enabled: true

springdoc:
    api-docs:
        enabled: true
    swagger-ui:
        enabled: true

openapi:
    service:
        api-docs: ott-education
        server: http://localhost:${server.port}
        title: OTT Education
        version: 1.0.0

jwt:
    expiryMinutes: 10080
    expiryDay: 7
    accessKey: vp/W0H2km+ha54EMwdU0lsVb8JNtoFrRlXVgytwhCsA=
    refreshKey: w+7+dny0YjqUN/bwKsejjgkBUdRUOeI7Liqr3jn2cqM=
    resetKey: nApgUJd322ox7k/x11ep43ew88T3lidT88NoGFXY1t0=
    resetPasswordExpiryMinutes: 10

app:
    frontend:
        url: http://localhost:5173

cloudinary:
    cloud:
        name: di7z5erbn
        api-key: '596182778278691'
        api-secret: tBjh2-Apc9GBwGxCBBrvotUTOB8

avatar:
    default: https://i.ibb.co/mrL8wYRs/default.jpg
